using System;

namespace PasTo {

    public class LanguageParse {
        private static string[] ubuntu = {"text",
            "Cucumber",
            "abap",
            "ada",
            "ahk",
            "antlr",
            "antlr-as",
            "antlr-cpp",
            "antlr-csharp",
            "antlr-java",
            "antlr-objc",
            "antlr-perl",
            "antlr-python",
            "antlr-ruby",
            "apacheconf",
            "applescript",
            "as",
            "as3",
            "aspx-cs",
            "aspx-vb",
            "asy",
            "basemake",
            "bash",
            "bat",
            "bbcode",
            "befunge",
            "blitzmax",
            "boo",
            "c",
            "c-objdump",
            "cfm",
            "cfs",
            "cheetah",
            "clojure",
            "cmake",
            "coffee-script",
            "common-lisp",
            "console",
            "control",
            "cpp",
            "cpp-objdump",
            "csharp",
            "css",
            "css+django",
            "css+erb",
            "css+genshitext",
            "css+mako",
            "css+myghty",
            "css+php",
            "css+smarty",
            "cython",
            "d",
            "d-objdump",
            "delphi",
            "diff",
            "django",
            "dpatch",
            "duel",
            "dylan",
            "erb",
            "erl",
            "erlang",
            "evoque",
            "factor",
            "felix",
            "fortran",
            "gas",
            "genshi",
            "genshitext",
            "glsl",
            "gnuplot",
            "go",
            "gooddata-cl",
            "groff",
            "haml",
            "haskell",
            "html",
            "html+cheetah",
            "html+django",
            "html+evoque",
            "html+genshi",
            "html+mako",
            "html+myghty",
            "html+php",
            "html+smarty",
            "html+velocity",
            "hx",
            "hybris",
            "ini",
            "io",
            "ioke",
            "irc",
            "jade",
            "java",
            "js",
            "js+cheetah",
            "js+django",
            "js+erb",
            "js+genshitext",
            "js+mako",
            "js+myghty",
            "js+php",
            "js+smarty",
            "jsp",
            "lhs",
            "lighty",
            "llvm",
            "logtalk",
            "lua",
            "make",
            "mako",
            "maql",
            "mason",
            "matlab",
            "matlabsession",
            "minid",
            "modelica",
            "modula2",
            "moocode",
            "mupad",
            "mxml",
            "myghty",
            "mysql",
            "nasm",
            "newspeak",
            "nginx",
            "numpy",
            "objdump",
            "objective-c",
            "objective-j",
            "ocaml",
            "ooc",
            "perl",
            "php",
            "postscript",
            "pot",
            "pov",
            "prolog",
            "properties",
            "protobuf",
            "py3tb",
            "pycon",
            "pytb",
            "python",
            "python3",
            "ragel",
            "ragel-c",
            "ragel-cpp",
            "ragel-d",
            "ragel-em",
            "ragel-java",
            "ragel-objc",
            "ragel-ruby",
            "raw",
            "rb",
            "rbcon",
            "rconsole",
            "rebol",
            "redcode",
            "rhtml",
            "rst",
            "sass",
            "scala",
            "scaml",
            "scheme",
            "scss",
            "smalltalk",
            "smarty",
            "sourceslist",
            "splus",
            "sql",
            "sqlite3",
            "squidconf",
            "ssp",
            "tcl",
            "tcsh",
            "tex",
            "text",
            "trac-wiki",
            "v",
            "vala",
            "vb.net",
            "velocity",
            "vim",
            "xml",
            "xml+cheetah",
            "xml+django",
            "xml+erb",
            "xml+evoque",
            "xml+mako",
            "xml+myghty",
            "xml+php",
            "xml+smarty",
            "xml+velocity",
            "xquery",
            "xslt",
            "yaml"
        };
        
        public static string[] ubuntuNames = { "Plain Text",
            "Gherkin",
            "ABAP",
            "Ada",
            "autohotkey",
            "ANTLR",
            "ANTLR With ActionScript Target",
            "ANTLR With CPP Target",
            "ANTLR With C# Target",
            "ANTLR With Java Target",
            "ANTLR With ObjectiveC Target",
            "ANTLR With Perl Target",
            "ANTLR With Python Target",
            "ANTLR With Ruby Target",
            "ApacheConf",
            "AppleScript",
            "ActionScript",
            "ActionScript 3",
            "aspx-cs",
            "aspx-vb",
            "Asymptote",
            "Makefile",
            "Bash",
            "Batchfile",
            "BBCode",
            "Befunge",
            "BlitzMax",
            "Boo",
            "C",
            "c-objdump",
            "Coldfusion HTML",
            "cfstatement",
            "Cheetah",
            "Clojure",
            "CMake",
            "CoffeeScript",
            "Common Lisp",
            "Bash Session",
            "Debian Control file",
            "C++",
            "cpp-objdump",
            "C#",
            "CSS",
            "CSS+Django/Jinja",
            "CSS+Ruby",
            "CSS+Genshi Text",
            "CSS+Mako",
            "CSS+Myghty",
            "CSS+PHP",
            "CSS+Smarty",
            "Cython",
            "D",
            "d-objdump",
            "Delphi",
            "Diff",
            "Django/Jinja",
            "Darcs Patch",
            "Duel",
            "Dylan",
            "ERB",
            "Erlang erl session",
            "Erlang",
            "Evoque",
            "Factor",
            "Felix",
            "Fortran",
            "GAS",
            "Genshi",
            "Genshi Text",
            "GLSL",
            "Gnuplot",
            "Go",
            "GoodData-CL",
            "Groff",
            "Haml",
            "Haskell",
            "HTML",
            "HTML+Cheetah",
            "HTML+Django/Jinja",
            "HTML+Evoque",
            "HTML+Genshi",
            "HTML+Mako",
            "HTML+Myghty",
            "HTML+PHP",
            "HTML+Smarty",
            "HTML+Velocity",
            "haXe",
            "Hybris",
            "INI",
            "Io",
            "Ioke",
            "IRC logs",
            "Jade",
            "Java",
            "JavaScript",
            "JavaScript+Cheetah",
            "JavaScript+Django/Jinja",
            "JavaScript+Ruby",
            "JavaScript+Genshi Text",
            "JavaScript+Mako",
            "JavaScript+Myghty",
            "JavaScript+PHP",
            "JavaScript+Smarty",
            "Java Server Page",
            "Literate Haskell",
            "Lighttpd configuration file",
            "LLVM",
            "Logtalk",
            "Lua",
            "Makefile",
            "Mako",
            "MAQL",
            "Mason",
            "Matlab",
            "Matlab session",
            "MiniD",
            "Modelica",
            "Modula-2",
            "MOOCode",
            "MuPAD",
            "MXML",
            "Myghty",
            "MySQL",
            "NASM",
            "Newspeak",
            "Nginx configuration file",
            "NumPy",
            "objdump",
            "Objective-C",
            "Objective-J",
            "OCaml",
            "Ooc",
            "Perl",
            "PHP",
            "PostScript",
            "Gettext Catalog",
            "POVRay",
            "Prolog",
            "Properties",
            "Protocol Buffer",
            "Python 3.0 Traceback",
            "Python console session",
            "Python Traceback",
            "Python",
            "Python 3",
            "Ragel",
            "Ragel in C Host",
            "Ragel in CPP Host",
            "Ragel in D Host",
            "Embedded Ragel",
            "Ragel in Java Host",
            "Ragel in Objective C Host",
            "Ragel in Ruby Host",
            "Raw token data",
            "Ruby",
            "Ruby irb session",
            "RConsole",
            "REBOL",
            "Redcode",
            "RHTML",
            "reStructuredText",
            "Sass",
            "Scala",
            "Scaml",
            "Scheme",
            "SCSS",
            "Smalltalk",
            "Smarty",
            "Debian Sourcelist",
            "S",
            "SQL",
            "sqlite3con",
            "SquidConf",
            "Scalate Server Page",
            "Tcl",
            "Tcsh",
            "TeX",
            "Text only",
            "MoinMoin/Trac Wiki markup",
            "verilog",
            "Vala",
            "VB.net",
            "Velocity",
            "VimL",
            "XML",
            "XML+Cheetah",
            "XML+Django/Jinja",
            "XML+Ruby",
            "XML+Evoque",
            "XML+Mako",
            "XML+Myghty",
            "XML+PHP",
            "XML+Smarty",
            "XML+Velocity",
            "XQuery",
            "XSLT",
            "YAML"
        };
        
        private static string[] pasteBin = { "text",
            "4cs",
            "6502acme",
            "6502kickass",
            "6502tasm",
            "abap",
            "actionscript",
            "actionscript3",
            "ada",
            "algol68",
            "apache",
            "applescript",
            "apt_sources",
            "arm",
            "asm",
            "asp",
            "asymptote",
            "autoconf",
            "autohotkey",
            "autoit",
            "avisynth",
            "awk",
            "bascomavr",
            "bash",
            "basic4gl",
            "bibtex",
            "blitzbasic",
            "bnf",
            "boo",
            "bf",
            "c",
            "c_mac",
            "cil",
            "csharp",
            "cpp",
            "cpp-qt",
            "c_loadrunner",
            "caddcl",
            "cadlisp",
            "cfdg",
            "chaiscript",
            "clojure",
            "klonec",
            "klonecpp",
            "cmake",
            "cobol",
            "coffeescript",
            "cfm",
            "css",
            "cuesheet",
            "d",
            "dcl",
            "dcpu16",
            "dcs",
            "delphi",
            "oxygene",
            "diff",
            "div",
            "dos",
            "dot",
            "e",
            "ecmascript",
            "eiffel",
            "email",
            "epc",
            "erlang",
            "fsharp",
            "falcon",
            "fo",
            "f1",
            "fortran",
            "freebasic",
            "freeswitch",
            "gambas",
            "gml",
            "gdb",
            "genero",
            "genie",
            "gettext",
            "go",
            "groovy",
            "gwbasic",
            "haskell",
            "haxe",
            "hicest",
            "hq9plus",
            "html4strict",
            "html5",
            "icon",
            "idl",
            "ini",
            "inno",
            "intercal",
            "io",
            "j",
            "java",
            "java5",
            "javascript",
            "jquery",
            "kixtart",
            "latex",
            "ldif",
            "lb",
            "lsl2",
            "lisp",
            "llvm",
            "locobasic",
            "logtalk",
            "lolcode",
            "lotusformulas",
            "lotusscript",
            "lscript",
            "lua",
            "m68k",
            "magiksf",
            "make",
            "mapbasic",
            "matlab",
            "mirc",
            "mmix",
            "modula2",
            "modula3",
            "68000devpac",
            "mpasm",
            "mxml",
            "mysql",
            "nagios",
            "newlisp",
            "nsis",
            "oberon2",
            "objeck",
            "objc",
            "ocaml-brief",
            "ocaml",
            "octave",
            "pf",
            "glsl",
            "oobas",
            "oracle11",
            "oracle8",
            "oz",
            "parasail",
            "parigp",
            "pascal",
            "pawn",
            "pcre",
            "per",
            "perl",
            "perl6",
            "php",
            "php-brief",
            "pic16",
            "pike",
            "pixelbender",
            "plsql",
            "postgresql",
            "povray",
            "powershell",
            "powerbuilder",
            "proftpd",
            "progress",
            "prolog",
            "properties",
            "providex",
            "purebasic",
            "pycon",
            "python",
            "pys60",
            "q",
            "qbasic",
            "rsplus",
            "rails",
            "rebol",
            "reg",
            "rexx",
            "robots",
            "rpmspec",
            "ruby",
            "gnuplot",
            "sas",
            "scala",
            "scheme",
            "scilab",
            "sdlbasic",
            "smalltalk",
            "smarty",
            "spark",
            "sparql",
            "sql",
            "stonescript",
            "systemverilog",
            "tsql",
            "tcl",
            "teraterm",
            "thinbasic",
            "typoscript",
            "unicon",
            "uscript",
            "ups",
            "urbi",
            "vala",
            "vbnet",
            "vedit",
            "verilog",
            "vhdl",
            "vim",
            "visualprolog",
            "vb",
            "visualfoxpro",
            "whitespace",
            "whois",
            "winbatch",
            "xbasic",
            "xml",
            "xorg_conf",
            "xpp",
            "yaml",
            "z80",
            "zxbasic"
        };
        
        public static string[] pasteBinNames = { "Plain Text",
            "4CS",
            "6502 ACME Cross Assembler",
            "6502 Kick Assembler",
            "6502 TASM/64TASS",
            "ABAP",
            "ActionScript",
            "ActionScript 3",
            "Ada",
            "ALGOL 68",
            "Apache Log",
            "AppleScript",
            "APT Sources",
            "ARM",
            "ASM (NASM)",
            "ASP",
            "Asymptote",
            "autoconf",
            "Autohotkey",
            "AutoIt",
            "Avisynth",
            "Awk",
            "BASCOM AVR",
            "Bash",
            "Basic4GL",
            "BibTeX",
            "Blitz Basic",
            "BNF",
            "BOO",
            "BrainFuck",
            "C",
            "C for Macs",
            "C Intermediate Language",
            "C#",
            "C++",
            "C++ (with QT extensions)",
            "C: Loadrunner",
            "CAD DCL",
            "CAD Lisp",
            "CFDG",
            "ChaiScript",
            "Clojure",
            "Clone C",
            "Clone C++",
            "CMake",
            "COBOL",
            "CoffeeScript",
            "ColdFusion",
            "CSS",
            "Cuesheet",
            "D",
            "DCL",
            "DCPU-16",
            "DCS",
            "Delphi",
            "Delphi Prism (Oxygene)",
            "Diff",
            "DIV",
            "DOS",
            "DOT",
            "E",
            "ECMAScript",
            "Eiffel",
            "Email",
            "EPC",
            "Erlang",
            "F#",
            "Falcon",
            "FO Language",
            "Formula One",
            "Fortran",
            "FreeBasic",
            "FreeSWITCH",
            "GAMBAS",
            "Game Maker",
            "GDB",
            "Genero",
            "Genie",
            "GetText",
            "Go",
            "Groovy",
            "GwBasic",
            "Haskell",
            "Haxe",
            "HicEst",
            "HQ9 Plus",
            "HTML",
            "HTML 5",
            "Icon",
            "IDL",
            "INI file",
            "Inno Script",
            "INTERCAL",
            "IO",
            "J",
            "Java",
            "Java 5",
            "JavaScript",
            "jQuery",
            "KiXtart",
            "Latex",
            "LDIF",
            "Liberty BASIC",
            "Linden Scripting",
            "Lisp",
            "LLVM",
            "Loco Basic",
            "Logtalk",
            "LOL Code",
            "Lotus Formulas",
            "Lotus Script",
            "LScript",
            "Lua",
            "M68000 Assembler",
            "MagikSF",
            "Make",
            "MapBasic",
            "MatLab",
            "mIRC",
            "MIX Assembler",
            "Modula 2",
            "Modula 3",
            "Motorola 68000 HiSoft Dev",
            "MPASM",
            "MXML",
            "MySQL",
            "Nagios",
            "newLISP",
            "NullSoft Installer",
            "Oberon 2",
            "Objeck Programming Langua",
            "Objective C",
            "OCalm Brief",
            "OCaml",
            "Octave",
            "OpenBSD PACKET FILTER",
            "OpenGL Shading",
            "Openoffice BASIC",
            "Oracle 11",
            "Oracle 8",
            "Oz",
            "ParaSail",
            "PARI/GP",
            "Pascal",
            "PAWN",
            "PCRE",
            "Per",
            "Perl",
            "Perl 6",
            "PHP",
            "PHP Brief",
            "Pic 16",
            "Pike",
            "Pixel Bender",
            "PL/SQL",
            "PostgreSQL",
            "POV-Ray",
            "Power Shell",
            "PowerBuilder",
            "ProFTPd",
            "Progress",
            "Prolog",
            "Properties",
            "ProvideX",
            "PureBasic",
            "PyCon",
            "Python",
            "Python for S60",
            "q/kdb+",
            "QBasic",
            "R",
            "Rails",
            "REBOL",
            "REG",
            "Rexx",
            "Robots",
            "RPM Spec",
            "Ruby",
            "Ruby Gnuplot",
            "SAS",
            "Scala",
            "Scheme",
            "Scilab",
            "SdlBasic",
            "Smalltalk",
            "Smarty",
            "SPARK",
            "SPARQL",
            "SQL",
            "StoneScript",
            "SystemVerilog",
            "T-SQL",
            "TCL",
            "Tera Term",
            "thinBasic",
            "TypoScript",
            "Unicon",
            "UnrealScript",
            "UPC",
            "Urbi",
            "Vala",
            "VB.NET",
            "Vedit",
            "VeriLog",
            "VHDL",
            "VIM",
            "Visual Pro Log",
            "VisualBasic",
            "VisualFoxPro",
            "WhiteSpace",
            "WHOIS",
            "Winbatch",
            "XBasic",
            "XML",
            "Xorg Config",
            "XPP",
            "YAML",
            "Z80 Assembler",
            "ZXBasic"
        };
        
        private static string[] pasteee = {"plain",
            "bash",
            "c",
            "cpp",
            "java",
            "javascript",
            "php",
            "python",
            "ruby",
            "abap",
            "algol68",
            "arm",
            "asm",
            "asp",
            "actionscript",
            "actionscript3",
            "ada",
            "apache",
            "applescript",
            "apt_sources",
            "autoit",
            "autoconf",
            "autohotkey",
            "avisynth",
            "bascomavr",
            "basic4gl",
            "bibtex",
            "blitzbasic",
            "boo",
            "bf",
            "c_loadrunner",
            "c_mac",
            "csharp",
            "cpp-qt",
            "caddcl",
            "cadlisp",
            "cfdg",
            "cil",
            "cmake",
            "cobol",
            "css",
            "chaiscript",
            "clojure",
            "coffeescript",
            "cfm",
            "cuesheet",
            "d",
            "dcl",
            "dcpu16",
            "dcs",
            "div",
            "dos",
            "delphi",
            "diff",
            "e",
            "ecmascript",
            "epc",
            "eiffel",
            "erlang",
            "euphoria",
            "fsharp",
            "fo",
            "falcon",
            "f1",
            "fortran",
            "freebasic",
            "freeswitch",
            "4cs",
            "gambas",
            "gdb",
            "gml",
            "gettext",
            "octave",
            "make",
            "genie",
            "gnuplot",
            "go",
            "groovy",
            "gwbasic",
            "hq9plus",
            "html4strict",
            "html5",
            "haskell",
            "haxe",
            "hicest",
            "ini",
            "intercal",
            "icon",
            "inno",
            "io",
            "j",
            "java5",
            "klonec",
            "klonecpp",
            "kixtart",
            "ldif",
            "llvm",
            "lolcode",
            "lsl2",
            "lscript",
            "latex",
            "lb",
            "lisp",
            "locobasic",
            "logtalk",
            "lotusformulas",
            "lotusscript",
            "lua",
            "mmix",
            "6502acme",
            "6502kickass",
            "6502tasm",
            "mxml",
            "magiksf",
            "mapbasic",
            "matlab",
            "mpasm",
            "reg",
            "modula2",
            "modula3",
            "68000devpac",
            "m68k",
            "mysql",
            "nsis",
            "nagios",
            "netrexx",
            "ocaml",
            "ocaml-brief",
            "oz",
            "oberon2",
            "objeck",
            "objc",
            "pf",
            "oobas",
            "oracle11",
            "oracle8",
            "oxygene",
            "parigp",
            "pcre",
            "php-brief",
            "pic16",
            "pli",
            "plsql",
            "povray",
            "properties",
            "parasail",
            "pascal",
            "pawnamxx",
            "perl",
            "perl6",
            "pike",
            "pixelbender",
            "postgresql",
            "powerbuilder",
            "powershell",
            "proftpd",
            "progress",
            "prolog",
            "providex",
            "purebasic",
            "pycon",
            "pys60",
            "qbasic",
            "rsplus",
            "rebol",
            "rpmspec",
            "rails",
            "sas",
            "spark",
            "sparql",
            "sql",
            "scala",
            "scheme",
            "scilab",
            "smalltalk",
            "smarty",
            "sourcepawn",
            "stonescript",
            "systemverilog",
            "tsql",
            "tcl",
            "teraterm",
            "text",
            "typoscript",
            "upc",
            "unicon",
            "idl",
            "uscript",
            "urbi",
            "vhdl",
            "vala",
            "vedit",
            "verilog",
            "vim",
            "vb",
            "visualfoxpro",
            "visualprolog",
            "whitespace",
            "whois",
            "winbatch",
            "xpp",
            "xbasic",
            "xml",
            "xorg_conf",
            "yaml",
            "zxbasic",
            "z80",
            "asymptote",
            "awk",
            "bnf",
            "dot",
            "email",
            "genero",
            "glsl",
            "jquery",
            "mirc",
            "newlisp",
            "oorexx",
            "per",
            "q",
            "rexx",
            "robots",
            "sdlbasic",
            "thinbasic",
            "vbnet"
        };
        
        public static string[] pasteeeNames =  {
            "Plain Text",
            "Bash",
            "C",
            "C++",
            "Java",
            "Javascript",
            "PHP",
            "Python",
            "Ruby",
            "ABAP",
            "ALGOL 68",
            "ARM ASSEMBLER",
            "ASM",
            "ASP",
            "ActionScript",
            "ActionScript 3",
            "Ada",
            "Apache configuration",
            "AppleScript",
            "Apt sources",
            "AutoIt",
            "Autoconf",
            "Autohotkey",
            "AviSynth",
            "BASCOM AVR",
            "Basic4GL",
            "BibTeX",
            "BlitzBasic",
            "Boo",
            "Brainfuck",
            "C (LoadRunner)",
            "C (Mac)",
            "C#",
            "C++ (Qt)",
            "CAD DCL",
            "CAD Lisp",
            "CFDG",
            "CIL",
            "CMake",
            "COBOL",
            "CSS",
            "ChaiScript",
            "Clojure",
            "CoffeeScript",
            "ColdFusion",
            "Cuesheet",
            "D",
            "DCL",
            "DCPU-16 Assembly",
            "DCS",
            "DIV",
            "DOS",
            "Delphi",
            "Diff",
            "E",
            "ECMAScript",
            "EPC",
            "Eiffel",
            "Erlang",
            "Euphoria",
            "F#",
            "FO (abas-ERP)",
            "Falcon",
            "Formula One",
            "Fortran",
            "FreeBasic",
            "FreeSWITCH",
            "GADV 4CS",
            "GAMBAS",
            "GDB",
            "GML",
            "GNU Gettext",
            "GNU Octave",
            "GNU make",
            "Genie",
            "Gnuplot",
            "Go",
            "Groovy",
            "GwBasic",
            "HQ9+",
            "HTML",
            "HTML5",
            "Haskell",
            "Haxe",
            "HicEst",
            "INI",
            "INTERCAL",
            "Icon",
            "Inno",
            "Io",
            "J",
            "Java(TM) 2 Platform Standard Edition 5.0",
            "KLone C",
            "KLone C++",
            "KiXtart",
            "LDIF",
            "LLVM Intermediate Representation",
            "LOLcode",
            "LSL2",
            "LScript",
            "LaTeX",
            "Liberty BASIC",
            "Lisp",
            "Locomotive Basic",
            "Logtalk",
            "Lotus Notes @Formulas",
            "LotusScript",
            "Lua",
            "MMIX",
            "MOS 6502 (6510) ACME Cross Assembler format",
            "MOS 6502 (6510) Kick Assembler format",
            "MOS 6502 (6510) TASM/64TASS 1.46 Assembler format",
            "MXML",
            "MagikSF",
            "MapBasic",
            "Matlab M",
            "Microchip Assembler",
            "Microsoft Registry",
            "Modula-2",
            "Modula-3",
            "Motorola 68000 - HiSoft Devpac ST 2 Assembler format",
            "Motorola 68000 Assembler",
            "MySQL",
            "NSIS",
            "Nagios",
            "NetRexx",
            "OCaml",
            "OCaml (brief)",
            "OZ",
            "Oberon-2",
            "Objeck Programming Language",
            "Objective-C",
            "OpenBSD Packet Filter",
            "OpenOffice.org Basic",
            "Oracle 11 SQL",
            "Oracle 8 SQL",
            "Oxygene (Delphi Prism)",
            "PARI/GP",
            "PCRE",
            "PHP (brief)",
            "PIC16",
            "PL/I",
            "PL/SQL",
            "POVRAY",
            "PROPERTIES",
            "ParaSail",
            "Pascal",
            "Pawn (AMXX)",
            "Perl",
            "Perl 6",
            "Pike",
            "Pixel Bender 1.0",
            "PostgreSQL",
            "PowerBuilder",
            "PowerShell",
            "ProFTPd configuration",
            "Progress",
            "Prolog",
            "ProvideX",
            "PureBasic",
            "Python (console mode)",
            "Python for S60",
            "QBasic/QuickBASIC",
            "R / S+",
            "REBOL",
            "RPM Specification File",
            "Rails",
            "SAS",
            "SPARK",
            "SPARQL",
            "SQL",
            "Scala",
            "Scheme",
            "SciLab",
            "Smalltalk",
            "Smarty",
            "SourcePawn",
            "StoneScript",
            "SystemVerilog",
            "T-SQL",
            "TCL",
            "Tera Term Macro",
            "Text",
            "TypoScript",
            "UPC",
            "Unicon (Unified Extended Dialect of Icon)",
            "Uno Idl",
            "Unreal Script",
            "Urbi",
            "VHDL",
            "Vala",
            "Vedit macro language",
            "Verilog",
            "Vim Script",
            "Visual Basic",
            "Visual Fox Pro",
            "Visual Prolog",
            "Whitespace",
            "Whois (RPSL format)",
            "Winbatch",
            "X++",
            "XBasic",
            "XML",
            "Xorg configuration",
            "YAML",
            "ZXBasic",
            "ZiLOG Z80 Assembler",
            "asymptote",
            "awk",
            "bnf",
            "dot",
            "eMail (mbox)",
            "genero",
            "glSlang",
            "jQuery",
            "mIRC Scripting",
            "newlisp",
            "ooRexx",
            "per",
            "q/kdb+",
            "rexx",
            "robots.txt",
            "sdlBasic",
            "thinBasic",
            "vb.net"
        };
        
        public static string getLangByIndex(int i, int bin) {
            switch(bin) {
                case 0:
                    if (i < ubuntu.Length)
                        return ubuntu[i];
                    break;
                case 1:
                    if (i < pasteBin.Length)
                        return pasteBin[i];
                    break;
                case 2:
                    if (i < pasteee.Length)
                        return pasteee[i];
                    break;
                default:
                    if (i < ubuntu.Length)
                        return ubuntu[i];
                    break;
            }
            return "";
        }
    }
}
